### PR TITLE
Update keybindings.md

### PR DESCRIPTION
**Pull request by metapho-re**
Correct keybinding to launch Powermenu

### CODE REVIEW

**Comment by angelofallars** [comment]
LGTM

**Comment by theCode-Breaker** [comment]
Same as #17

**Comment by metapho-re** [comment]
@theCode-Breaker It's the same info as in the README, just noticed it should be corrected here as well.

**Comment by theCode-Breaker** [comment]
@metapho-re https://github.com/metapho-re/axyl-iso/tree/master is 3 commits behind and the keybinding is already fixed

**Comment by theCode-Breaker** [comment]
PR #17 was merged

**Comment by metapho-re** [comment]
It fixes a different file...

**Comment by theCode-Breaker** [comment]
Okay got it

**Comment by theCode-Breaker** [comment]
@Kungger-git merge this please

**Pull request merged**
